title = 'Stream Notes'
baseURL = 'http://localhost:1313/'
author = 'Taylor Smith'
languageCode = 'en-us'
theme = 'hugo-book'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
writeStats = true
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode and raw HTML/scripts in writeups
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  BookTheme = 'light'
  BookSection = 'docs'
  BookRepo = 'https://github.com/tsmith512/stream-notes'
  BookSearch = false
